/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package condominium.electricity.meter.management.system;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mohammad
 */
public class ShowUsage extends javax.swing.JPanel {

    /**
     * Creates new form ShowUsage
     */
    public ShowUsage() {
        initComponents();
    }
    public void loadUsage()
    {
        int tuse=0;
        int tpay=0;
        TaskManager ts= new TaskManager();
         jTable1.removeAll();
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         model.getDataVector().removeAllElements();
         ArrayList<ArrayList<Integer>> details;
        model.setRowCount(0);
        try {
            // TODO add your handling code here:
            int usage=0;
            int pay=0;
            details=ts.getUsages("1");
            for(int i=0;i<details.size();i++)
            {
                usage+=details.get(i).get(1);
                pay+=details.get(i).get(2);
            }
            model.addRow(new Object[]{"NO.1", usage, pay});
            tuse+=usage;
            tpay+=pay;
            usage=0;
            pay=0;
            details=ts.getUsages("2");
            for(int i=0;i<details.size();i++)
            {
                usage+=details.get(i).get(1);
                pay+=details.get(i).get(2);
            }
            model.addRow(new Object[]{"NO.2", usage, pay});
             tuse+=usage;
            tpay+=pay;
            usage=0;
            pay=0;
            details=ts.getUsages("3");
            for(int i=0;i<details.size();i++)
            {
                usage+=details.get(i).get(1);
                pay+=details.get(i).get(2);
            }
            model.addRow(new Object[]{"NO.3", usage, pay});
             tuse+=usage;
            tpay+=pay;
            usage=0;
            pay=0;
            details=ts.getUsages("4");
            for(int i=0;i<details.size();i++)
            {
                usage+=details.get(i).get(1);
                pay+=details.get(i).get(2);
            }
            model.addRow(new Object[]{"NO.4", usage, pay});
             tuse+=usage;
            tpay+=pay;
            usage=0;
            pay=0;
            details=ts.getUsages("5");
            for(int i=0;i<details.size();i++)
            {
                usage+=details.get(i).get(1);
                pay+=details.get(i).get(2);
            }
            model.addRow(new Object[]{"NO.5", usage, pay});
             tuse+=usage;
            tpay+=pay;
            usage=0;
            pay=0;
            details=ts.getUsages("6");
            for(int i=0;i<details.size();i++)
            {
                usage+=details.get(i).get(1);
                pay+=details.get(i).get(2);
            }
            model.addRow(new Object[]{"NO.6", usage, pay});
             tuse+=usage;
            tpay+=pay;
            usage=0;
            pay=0;
            details=ts.getUsages("7");
            for(int i=0;i<details.size();i++)
            {
                usage+=details.get(i).get(1);
                pay+=details.get(i).get(2);
            }
            model.addRow(new Object[]{"NO.7", usage, pay});
             tuse+=usage;
            tpay+=pay;
            usage=0;
            pay=0;
            details=ts.getUsages("8");
            for(int i=0;i<details.size();i++)
            {
                usage+=details.get(i).get(1);
                pay+=details.get(i).get(2);
            }
            model.addRow(new Object[]{"NO.8", usage, pay});
             tuse+=usage;
            tpay+=pay;
            usage=0;
            pay=0;
            details=ts.getUsages("9");
            for(int i=0;i<details.size();i++)
            {
                usage+=details.get(i).get(1);
                pay+=details.get(i).get(2);
            }
            model.addRow(new Object[]{"NO.9", usage, pay});
             tuse+=usage;
            tpay+=pay;
            usage=0;
            pay=0;
            details=ts.getUsages("10");
            for(int i=0;i<details.size();i++)
            {
                usage+=details.get(i).get(1);
                pay+=details.get(i).get(2);
            }
            model.addRow(new Object[]{"NO.10", usage, pay});
            
            jLabel3.setText(tuse+" KW");
            jLabel5.setText(tpay+" RM");
        }
        catch(Exception ex)
        {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(600, 500));
        setMinimumSize(new java.awt.Dimension(600, 500));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("UNITS USAGES");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UNIT NUMBER", "USAGE", "PAYMENT"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Total Usage:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("-");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Total Payment:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 89, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(70, 70, 70)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        this.setVisible(false);
    }                                        


    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration                   
}
