/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg7seas;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mohammad
 */
public class Freight_Edit extends javax.swing.JPanel {

    /**
     * Creates new form Client_View
     */
    ArrayList<ArrayList<String>> details=new  ArrayList<ArrayList<String>>();
    File Fre = new File("Fre.txt");
     File tFre = new File("tFre.txt");
    public Freight_Edit() {
        initComponents();
    }
    public void fillTable() throws FileNotFoundException
    {
        details.clear();
         jTable1.removeAll();
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         model.getDataVector().removeAllElements();
         model.setRowCount(0);
        Scanner FileScanner = new Scanner(Fre);
        String cus,ro,cl,ports,dis,typ,we,pr;
        String name , ph;
        while ( FileScanner.hasNext()){
            ArrayList<String> det=new ArrayList<String>();
            cus = FileScanner.next().replace('?', ' ');
            ro = FileScanner.next().replace('?', ' ');
            cl = FileScanner.next().replace('?', ' ');
            ports = FileScanner.next();
            dis = FileScanner.next();
            typ = FileScanner.next();
            we = FileScanner.next();
            pr = FileScanner.next();
            det.add(cus);
            det.add(ro);
            det.add(cl);
            det.add(we);
            det.add(pr);
            details.add(det);
            model.addRow(new Object[]{cus,ro,cl,ports,dis,typ});
        }
        FileScanner.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("FRIEGHT EDIT");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CUSTOMER", "ROUT", "CLIENT", "PORTS", "DISTANCE", "TYPE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 0, 0));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("Weight:");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 153));
        jLabel11.setText("TL");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("Price:");

        jTextField4.setEnabled(false);
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 0, 153));
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 0, 0));
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("Enter All The Information");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 35, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel10)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        // TODO add your handling code here:
        int w=0;
        jLabel10.setVisible(false);
        try
        {
            
            w=Integer.parseInt(jTextField3.getText().toString());
        }catch(Exception ex){
            jLabel10.setText("Invalid Weight");
            jTextField4.setText("0");
            jLabel10.setVisible(true);
            return;
        }
        if(w<=7000)
        jLabel11.setText("LTL");
        else
        jLabel11.setText("TL");
        /*
        Conteiner 0.01 0.015
        Barge     0.02 0.025
        Tankers   0.03 0.035
        Tugboats  0.04 0.045
        Cargo     0.05 0.055
        Cruses    0.06 0.065
        */
        int dis=0;
        try
        {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            int row=jTable1.getSelectedRow();
            dis=Integer.parseInt(model.getValueAt(row, 4).toString());
       
        double rate=0;
        if(model.getValueAt(row, 5).toString().equals("Conteiner")) rate=0.01;
        else if(model.getValueAt(row, 5).toString().equals("Barge")) rate=0.02;
        else if(model.getValueAt(row, 5).toString().equals("Tankers")) rate=0.03;
        else if(model.getValueAt(row, 5).toString().equals("Tugboats")) rate=0.04;
        else if(model.getValueAt(row, 5).toString().equals("Cargo")) rate=0.05;
        else rate=0.06;
        if(jLabel11.getText().equals("LTL")) rate+=0.005;
        double price=rate*dis*w;
        jTextField4.setText(price+"");
        }
        catch(Exception ex){return;}
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField4KeyPressed

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int row=jTable1.getSelectedRow();
        String cus=model.getValueAt(row, 0).toString().replace(' ', '?');
        String ro=model.getValueAt(row, 1).toString().replace(' ', '?');
        String cl=model.getValueAt(row, 2).toString().replace(' ', '?');
        String ports=model.getValueAt(row, 3).toString().replace(' ', '?');
        String dis=model.getValueAt(row, 4).toString();
        String typ=model.getValueAt(row, 5).toString();
        String we=jTextField3.getText();
        String pr=jTextField4.getText();
        
        
        
        try
        {
        Scanner FileScanner = new Scanner(Fre);
        BufferedWriter bw = new BufferedWriter( new FileWriter (tFre , false));
        String cu,r,c,po,di,ty,w,p;
        while ( FileScanner.hasNext()){
            cu = FileScanner.next();
            r = FileScanner.next();
             c = FileScanner.next();
            po = FileScanner.next();
             di = FileScanner.next();
            ty = FileScanner.next();
            w = FileScanner.next();
            p = FileScanner.next();
            if(cu.equals(cus) && r.equals(ro) && c.equals(cl))
            {
                bw.write(cu+" "+ r+ " " +c+" "+po+" "+di+" "+ty+" "+we+" "+pr);
            }
            else
             bw.write(cu+" "+ r+ " " +c+" "+po+" "+di+" "+ty+" "+w+" "+p);
             bw.newLine();
        }
        bw.close();
        FileScanner.close();
        FileScanner = new Scanner(tFre);
        bw = new BufferedWriter( new FileWriter (Fre , false));

        while ( FileScanner.hasNext()){
            cu = FileScanner.next();
            r = FileScanner.next();
             c = FileScanner.next();
            po = FileScanner.next();
             di = FileScanner.next();
            ty = FileScanner.next();
            w = FileScanner.next();
            p = FileScanner.next();
             bw.write(cu+" "+ r+ " " +c+" "+po+" "+di+" "+ty+" "+w+" "+p);
             bw.newLine();
        }
        bw.close();
        FileScanner.close();
        }catch(Exception ex){}
        

        

    
        jTextField3.setText("");
        jTextField4.setText("");
        JOptionPane.showMessageDialog(this, "The Freight Has Been Updated Successfuly");
        this.setVisible(false);
        }
        catch(Exception ex){}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try
        {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int row=jTable1.getSelectedRow();
        String cus=model.getValueAt(row, 0).toString().replace(' ', '?');
        String ro=model.getValueAt(row, 1).toString().replace(' ', '?');
        String cl=model.getValueAt(row, 2).toString().replace(' ', '?');
        String ports=model.getValueAt(row, 3).toString().replace(' ', '?');
        
        
        
        try
        {
        Scanner FileScanner = new Scanner(Fre);
        BufferedWriter bw = new BufferedWriter( new FileWriter (tFre , false));
        String cu,r,c,po,di,ty,w,p;
        while ( FileScanner.hasNext()){
            cu = FileScanner.next();
            r = FileScanner.next();
             c = FileScanner.next();
            po = FileScanner.next();
             di = FileScanner.next();
            ty = FileScanner.next();
            w = FileScanner.next();
            p = FileScanner.next();
            if(cu.equals(cus) && r.equals(ro) && c.equals(cl))
            {
                //bw.write(cu+" "+ r+ " " +c+" "+po+" "+di+" "+ty+" "+we+" "+pr);
            }
            else
             bw.write(cu+" "+ r+ " " +c+" "+po+" "+di+" "+ty+" "+w+" "+p);
             bw.newLine();
        }
        bw.close();
        FileScanner.close();
        FileScanner = new Scanner(tFre);
        bw = new BufferedWriter( new FileWriter (Fre , false));

        while ( FileScanner.hasNext()){
            cu = FileScanner.next();
            r = FileScanner.next();
             c = FileScanner.next();
            po = FileScanner.next();
             di = FileScanner.next();
            ty = FileScanner.next();
            w = FileScanner.next();
            p = FileScanner.next();
             bw.write(cu+" "+ r+ " " +c+" "+po+" "+di+" "+ty+" "+w+" "+p);
             bw.newLine();
        }
        bw.close();
        FileScanner.close();
        }catch(Exception ex){}
        

        

    
        jTextField3.setText("");
        jTextField4.setText("");
        JOptionPane.showMessageDialog(this, "The Freight Has Been Deleted Successfuly");
        this.setVisible(false);
        }
        catch(Exception ex){}

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        try
        {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int row=jTable1.getSelectedRow();
        String cus=model.getValueAt(row, 0).toString();
        String ro=model.getValueAt(row, 1).toString();
        String cl=model.getValueAt(row, 2).toString();
        for(int i=0;i<details.size();i++)
        {
            if(details.get(i).get(0).equals(cus)&&
                    details.get(i).get(1).equals(ro) &&
                    details.get(i).get(2).equals(cl))
            {
                jTextField3.setText(details.get(i).get(3));
                jTextField4.setText(details.get(i).get(4));
            }
        }
        }
        catch(Exception ex){}
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
