/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package attendance.managment;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.util.Formatter;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mohammad
 */
public class CheckRequests extends javax.swing.JPanel {

    /**
     * Creates new form CheckRequests
     */
    public CheckRequests() {
        initComponents();
    }
    public void init()
    {
        File reason= new File("reason.txt");
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         model.getDataVector().removeAllElements();
         try
         {
            Scanner fs= new Scanner(reason);
            
            while(fs.hasNext())
            {
                   String details=fs.next();
                   String userName=fs.next();
                   String rea=fs.next();
                   String stat=fs.next();
                   if(stat.equals("PENDING"))
                   {
                       String[] tempSplit=details.split("_");
                       String subject=tempSplit[0];
                       String date=tempSplit[1]+"/"+tempSplit[2]+"/"+tempSplit[3];
                       String time=tempSplit[4]+":"+tempSplit[5].replace(".txt","");
                       model.addRow(new Object[]{userName, subject,date,time,rea.replace("%%"," ")});
                   }
             }
             fs.close();
         }catch(Exception ex){}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(600, 500));
        setMinimumSize(new java.awt.Dimension(600, 500));
        setPreferredSize(new java.awt.Dimension(600, 500));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("CHECK REQUESTS");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STUDENT", "SUBJECT", "DATE", "TIME", "REASON"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 204, 0));
        jButton1.setText("ACCEPT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("REJECT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        update("ACCEPT");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        update("REJECT");
    }//GEN-LAST:event_jButton2ActionPerformed
    public void update(String st)
    {
        int index=jTable1.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String details_=model.getValueAt(index,1).toString()+"_"+
                model.getValueAt(index,2).toString().replace("/","_")+"_"+
                model.getValueAt(index,3).toString().replace(":", "_");
        String userName_=model.getValueAt(index,0).toString();
        File reason= new File("reason.txt");
        File treason=new File("treason.txt");
        
         try
         {
            Scanner fs= new Scanner(reason);
            BufferedWriter fw= new BufferedWriter(new FileWriter(treason,false));
            while(fs.hasNext())
            {
                   String details=fs.next();
                   String userName=fs.next();
                   String rea=fs.next();
                   String stat=fs.next();
                   if(userName.equals(userName_))
                       stat=st;
                   fw.write(details+" "+userName+" "+rea+" "+stat);
                   fw.newLine();
             }
             fs.close();
             fw.close();
         }catch(Exception ex){}
         try
         {
            Scanner fs= new Scanner(treason);
            BufferedWriter fw= new BufferedWriter(new FileWriter(reason,false));
            while(fs.hasNext())
            {
                   String details=fs.next();
                   String userName=fs.next();
                   String rea=fs.next();
                   String stat=fs.next();
                   fw.write(details+" "+userName+" "+rea+" "+stat);
                   fw.newLine();
             }
             fs.close();
             fw.close();
         }catch(Exception ex){}
        if(st.equals("REJECT"))
        {
            JOptionPane.showMessageDialog(this, "The Request Has Been Rejected.");
            this.setVisible(false);
            return;
        }
        File temp= new File("temp.txt");
        if(!temp.exists())
        {
            try
            {
                final Formatter y;
                y= new Formatter ("temp.txt");
                y.close();
            }catch(Exception ex){}
        }
        File att=new File("ATT\\"+details_+".txt");
        try
        {
            Scanner fs= new Scanner(att);
            BufferedWriter fw= new BufferedWriter(new FileWriter(temp,false));
            while(fs.hasNext())
            {
                   String usNa=fs.next();
                   String att_=fs.next();
                   String reason_=fs.next();
                   if(usNa.equals(userName_))
                   {
                        fw.write(usNa+" "+"ABSENT-WITH-REASON"+" "+reason_);
                   }
                   else
                       fw.write(usNa+" "+att_+" "+reason_);
                   fw.newLine();
             }
             fs.close();
             fw.close();
         }catch(Exception ex){}
         try
        {
            Scanner fs= new Scanner(temp);
            BufferedWriter fw= new BufferedWriter(new FileWriter(att,false));
            while(fs.hasNext())
            {
                   String usNa=fs.next();
                   String att_=fs.next();
                   String reason_=fs.next();
                   fw.write(usNa+" "+att_+" "+reason_);
                   fw.newLine();
             }
             fs.close();
             fw.close();
         }catch(Exception ex){}
         JOptionPane.showMessageDialog(this, "The Attendance Has Been Updated.");
         this.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
